version: "3.9"

services:
  db:
    image: postgres:15 
    container_name: pias_postgres
    restart: always
    environment:
      POSTGRES_USER: pias123
      POSTGRES_PASSWORD: pias123
      POSTGRES_DB: pias_db
    ports:
      - "5432:5432"
    volumes:
      - qc_data:/var/lib/postgresql/data

volumes:
  qc_data:
